package es.mde.ControlPersonalLIB.permisos.tipoPermiso;

public enum TiposPermiso {
	VACACIONES,
	ASUNTOS_PROPIOS,
	DESCANSO_OBLIGATORIO,
	DESCANSO_ADICIONAL,
	DESCANSO_PREPARACION,
	PERMISO_EXTRAORDINARIO
}
